# Generated by Django 5.1.2 on 2024-11-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrating',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rating', to='app.answer'),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rating', to='app.question'),
        ),
    ]
